### ISSUE TITLE
NSST Analysis

### ISSUE THREAD

**Issue by guillaumevernieres** [NOAA-EMC/godas#487]
## Description
As we have seen an improvement in "o-b" for AVHRR in the WCDA test, the next step it to check if we see a similar improvement in the foundation temperature analysis.  

### Tasks 
- [ ] Get the Tref analysis: Add the tref increment to the background
- [ ] Interpolate to the MOM6 grid
- [ ] Analyse results: Generate global time series and maps of omb's, compare against MOM6 and ops tref ...

**Comment by AndrewEichmann-NOAA** [comment]
@guillaumevernieres So what precisely do you want compared - atmospheric tref analyses vs. mom6 vs. ops vs. ostia? How do ombs figure in?

**Comment by guillaumevernieres** [comment]
> @guillaumevernieres So what precisely do you want compared - atmospheric tref analyses vs. mom6 vs. ops vs. ostia? How do ombs figure in?

@AndrewEichmann-NOAA , sorry for seeing this so late. Comparison against ostia is what we've been doing so far. Are the tref analysis saved on the mom6 grid? if so, send me the path, I can at least plot the time series of global stats.

**Comment by AndrewEichmann-NOAA** [comment]
@guillaumevernieres Should have that today. Do you have any preference as to having it land-masked with nans or zeros? Or have the unmasked field, but with the mask as a separated field?

**Comment by AndrewEichmann-NOAA** [comment]
@guillaumevernieres Would you know why the ocean forecasts have coordinates like this:
```
(gdasapp) -bash-4.2$ ncdump -h golden-c384/golden-c384/gdas.20210715/00/ocean/gdas.t00z.ocnf003.nc 
netcdf gdas.t00z.ocnf003 {
dimensions:
	xh = 1440 ;
	yh = 1080 ;
	time = UNLIMITED ; // (1 currently)
	xq = 1440 ;
	zl = 75 ;
	yq = 1080 ;
variables:
	double xh(xh) ;
		xh:units = "degrees_east" ;
		xh:long_name = "h point nominal longitude" ;
		xh:axis = "X" ;
	double yh(yh) ;
		yh:units = "degrees_north" ;
		yh:long_name = "h point nominal latitude" ;
		yh:axis = "Y" ;
```
...but the ocean analysis has these coordinates?
```
(gdasapp) -bash-4.2$ ncdump -h golden-c384/golden-c384/gdas.20210715/00/ocean/gdas.t00z.ocnana.nc
netcdf gdas.t00z.ocnana {
dimensions:
	xaxis_1 = 1440 ;
	yaxis_1 = 1080 ;
	zaxis_1 = 75 ;
	Time = UNLIMITED ; // (1 currently)
variables:
	double xaxis_1(xaxis_1) ;
		xaxis_1:long_name = "xaxis_1" ;
		xaxis_1:units = "none" ;
		xaxis_1:cartesian_axis = "X" ;
	double yaxis_1(yaxis_1) ;
		yaxis_1:long_name = "yaxis_1" ;
		yaxis_1:units = "none" ;
		yaxis_1:cartesian_axis = "Y" ;
```
(these are in your space)

**Comment by guillaumevernieres** [comment]
@AndrewEichmann-NOAA  the top one is written as a history file, the bottom one as a restart. Same geometry/grid though.

**Comment by AndrewEichmann-NOAA** [comment]
@guillaumevernieres xaxis_1 and yaxis_1 are filled with integers, array indices, not lat/lons. No big deal, I'll use the forecast, but it's another surprise

**Comment by guillaumevernieres** [comment]
> @guillaumevernieres xaxis_1 and yaxis_1 are filled with integers, array indices, not lat/lons. No big deal, I'll use the forecast, but it's another surprise

just to be clear again @AndrewEichmann-NOAA , none of these 1D array represent the horizontal geometry of mom6.

**Comment by AndrewEichmann-NOAA** [comment]
I have interpolated tref analyses under /`scratch1/NCEPDEV/stmp4/Andrew.Eichmann/golden-c384`, in the form `gdas.t{cyc}z.trefanlmom6.nc/` . They have two fields in them: trefanl which is interpolated everywhere, and trefanlocn, which has an ocean mask applied (and everything else set to nans) before interpolating, to provide some flexibility if wanted.
